#if RPG_ESSENTIALS_GENERATOR
using RhoMicro.CodeAnalysis;
#endif

namespace RPG.SourceGenerator.Attributes;

/// <summary>
/// An attribute used to indicate that a method or property should be excluded from extension methods
/// generated by the RPGEntityExtensionGenerator.
/// </summary>
/// <remarks>
/// Applying this attribute to a method or property prevents it from being considered for inclusion
/// in the generated extension methods by tools or utilities that check for this specific attribute.
/// </remarks>
/// <example>
/// This attribute can be applied to both methods and properties.
/// When applied, the annotated members will be ignored during the generation of extension methods.
/// </example>
#if RPG_ESSENTIALS_GENERATOR
[IncludeFile]
#endif
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property)]
internal class ExcludeFromExtensionsAttribute : Attribute;
