using GameAccessTools.SourceGenerator.Attributes;
using Pokemon.Data.Model.HardCoded;
using UnrealSharp.CoreUObject;

namespace Pokemon.Data;

[StaticIdentifier<FGrowthRate>("Medium", "Erratic", "Fluctuating", "Parabolic", "Fast", "Slow")]
[StaticIdentifier<FGenderRatio>(
    "AlwaysMale",
    "AlwaysFemale",
    "Genderless",
    "FemaleOneEighth",
    "Female25Percent",
    "Female50Percent",
    "Female75Percent",
    "FemaleSevenEighths"
)]
[StaticIdentifier<FEggGroup>(
    "Undiscovered",
    "Monster",
    "Water1",
    "Bug",
    "Flying",
    "Field",
    "Fairy",
    "Grass",
    "Humanlike",
    "Water3",
    "Mineral",
    "Amorphous",
    "Water2",
    "Ditto",
    "Dragon"
)]
[StaticIdentifier<FBodyShape>(
    "Head",
    "Serpentine",
    "Finned",
    "HeadArms",
    "HeadBase",
    "BipedalTail",
    "HeadLegs",
    "Quadruped",
    "Winged",
    "Multiped",
    "MultiBody",
    "Bipedal",
    "MultiWinged",
    "Insectoid"
)]
[StaticIdentifier<FBodyColor>(
    "Red",
    "Blue",
    "Yellow",
    "Green",
    "Black",
    "Brown",
    "Purple",
    "Gray",
    "White",
    "Pink"
)]
[StaticIdentifier<FHabitat>(
    "Grassland",
    "Forest",
    "WatersEdge",
    "Sea",
    "Cave",
    "Mountain",
    "RoughTerrain",
    "Urban",
    "Rare"
)]
[StaticIdentifier<FEvolution>(
    "Level",
    "LevelMale",
    "LevelFemale",
    "LevelDay",
    "LevelNight",
    "LevelMorning",
    "LevelAfternoon",
    "LevelEvening",
    "LevelNoWeather",
    "LevelSun",
    "LevelRain",
    "LevelSnow",
    "LevelSandstorm",
    "LevelCycling",
    "LevelSurfing",
    "LevelDiving",
    "LevelDarkness",
    "LevelDarkInParty",
    "AttackGreater",
    "AtkDefEqual",
    "DefenseGreater",
    "Silcoon",
    "Cascoon",
    "Ninjask",
    "Shedinja",
    "Happiness",
    "HappinessMale",
    "HappinessFemale",
    "HappinessDay",
    "HappinessNight",
    "HappinessMove",
    "HappinessMoveType",
    "HappinessHoldItem",
    "MaxHappiness",
    "Beauty",
    "HoldItem",
    "HoldItemMale",
    "HoldItemFemale",
    "DayHoldItem",
    "NightHoldItem",
    "HoldItemHappiness",
    "HasMove",
    "HasMoveType",
    "HasInParty",
    "Location",
    "LocationFlag",
    "Region",
    "Item",
    "ItemMale",
    "ItemFemale",
    "ItemDay",
    "ItemNight",
    "ItemHappiness",
    "Trade",
    "TradeMale",
    "TradeFemale",
    "TradeDay",
    "TradeNight",
    "TradeItem",
    "TradeSpecies",
    "BattleDealCriticalHit",
    "Event",
    "EventAfterDamageTaken"
)]
[StaticIdentifier<FStat>(
    "HP",
    "ATTACK",
    "DEFENSE",
    "SPECIAL_ATTACK",
    "SPECIAL_DEFENSE",
    "SPEED",
    "ACCURACY",
    "EVASION"
)]
[StaticIdentifier<FNature>(
    "HARDY",
    "LONELY",
    "BRAVE",
    "ADAMANT",
    "NAUGHTY",
    "BOLD",
    "DOCILE",
    "RELAXED",
    "IMPISH",
    "LAX",
    "TIMID",
    "HASTY",
    "SERIOUS",
    "JOLLY",
    "NAIVE",
    "MODEST",
    "MILD",
    "QUIET",
    "BASHFUL",
    "RASH",
    "CALM",
    "GENTLE",
    "SASSY",
    "CAREFUL",
    "QUIRKY"
)]
[StaticIdentifier<FStatus>("SLEEP", "POISON", "BURN", "PARALYSIS", "FROZEN")]
[StaticIdentifier<FFieldWeather>(
    "Rain",
    "Storm",
    "Snow",
    "Blizzard",
    "Sandstorm",
    "HeavyRain",
    "Sun",
    "Fog"
)]
[StaticIdentifier<FEncounterType>(
    "Land",
    "LandDay",
    "LandNight",
    "LandMorning",
    "LandAfternoon",
    "LandEvening",
    "PokeRadar",
    "Cave",
    "CaveDay",
    "CaveNight",
    "CaveMorning",
    "CaveAfternoon",
    "CaveEvening",
    "Water",
    "WaterDay",
    "WaterNight",
    "WaterMorning",
    "WaterAfternoon",
    "WaterEvening",
    "OldRod",
    "GoodRod",
    "SuperRod",
    "RockSmash",
    "HeadbuttLow",
    "HeadbuttHigh",
    "BugContest"
)]
[StaticIdentifier<FEnvironment>(
    "Grass",
    "TallGrass",
    "MovingWater",
    "StillWater",
    "Puddle",
    "Underwater",
    "Cave",
    "Rock",
    "Sand",
    "Forest",
    "ForestGrass",
    "Snow",
    "Ice",
    "Volcano",
    "Graveyard",
    "Sky",
    "Space",
    "UltraSpace"
)]
[StaticIdentifier<FBattleWeather>(
    "Sun",
    "Rain",
    "Sandstorm",
    "Hail",
    "HarshSun",
    "HeavyRain",
    "StrongWinds",
    "ShadowSky"
)]
[StaticIdentifier<FBattleTerrain>("Electric", "Grassy", "Misty", "Psychic")]
[StaticIdentifier<FTarget>(
    "User",
    "NearAlly",
    "UserOrNearAlly",
    "AllAllies",
    "UserAndAllies",
    "NearFoe",
    "RandomNearFoe",
    "AllNearFoes",
    "Foe",
    "AllFoes",
    "NearOther",
    "AllNearOthers",
    "Other",
    "AllBattlers",
    "UserSide",
    "FoeSide",
    "BothSides"
)]
public static partial class IdentifierConstants
{
    public const string FunctionCodeTag = "Battle.Move.FunctionCode";
    public const string BattleUseTag = "Battle.Item.Use";
    public const string PocketTag = "Item.Pocket";
}
