//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG.SourceGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG.SourceGenerator.Properties.SourceTemplates", typeof(SourceTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable enable
        ///using static UnrealSharp.Interop.FTypeBuilderExporter;
        ///using static UnrealSharp.Interop.FPropertyExporter;
        ///using static UnrealSharp.Interop.UClassExporter;
        ///using static UnrealSharp.Interop.UFunctionExporter;
        ///
        ///using UnrealSharp;
        ///using UnrealSharp.Core;
        ///using UnrealSharp.Attributes;
        ///using UnrealSharp.RPGCore;
        ///using UnrealSharp.RPGSaving;
        ///using System.Runtime.CompilerServices;
        ///
        ///namespace {{Namespace}};
        ///
        ///partial class {{ClassName}}
        ///{
        ///    protected override bool Supports_Impleme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComponentSaverTemplate {
            get {
                return ResourceManager.GetString("ComponentSaverTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using static UnrealSharp.Interop.FTypeBuilderExporter;
        ///using static UnrealSharp.Interop.FPropertyExporter;
        ///using static UnrealSharp.Interop.UClassExporter;
        ///using static UnrealSharp.Interop.UFunctionExporter;
        ///using static System.ComponentModel.EditorBrowsableState;
        ///
        ///using UnrealSharp;
        ///using UnrealSharp.Core;
        ///using UnrealSharp.Core.Attributes;
        ///using UnrealSharp.Core.Marshallers;
        ///using UnrealSharp.Interop;
        ///using UnrealSharp.Attributes;
        ///using UnrealSharp.Attributes.MetaTags;
        ///using UnrealSharp.Engine;
        ///using Unre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RPGEntityBlueprintLibraryTemplate {
            get {
                return ResourceManager.GetString("RPGEntityBlueprintLibraryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using UnrealSharp;
        ///using UnrealSharp.Attributes;
        ///using UnrealSharp.Attributes.MetaTags;
        ///using UnrealSharp.Engine;
        ///using UnrealSharp.RPGCore;
        ///
        ///namespace {{Namespace}};
        ///
        ///public static partial class {{EngineName}}Extensions 
        ///{
        ///    extension({{ClassName}} unit)
        ///    {
        ///        {{#Components}}
        ///        {{#Properties}}
        ///        public {{Type}} {{Name}} 
        ///        {
        ///            {{#HasGetter}}
        ///            get =&gt; unit.{{../ComponentName}}.{{Name}};
        ///            {{/HasGetter}}
        ///            {{#HasSetter}}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RPGEntityExtensionsTemplate {
            get {
                return ResourceManager.GetString("RPGEntityExtensionsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using static UnrealSharp.Interop.FTypeBuilderExporter;
        ///using static UnrealSharp.Interop.FPropertyExporter;
        ///using static UnrealSharp.Interop.UClassExporter;
        ///using static UnrealSharp.Interop.UFunctionExporter;
        ///
        ///using UnrealSharp;
        ///using UnrealSharp.Core;
        ///using UnrealSharp.Attributes;
        ///using UnrealSharp.CoreUObject;
        ///using UnrealSharp.Engine;
        ///using UnrealSharp.RPGCore;
        ///using GameDataAccessTools.Core.Utilities;
        ///using System.Runtime.CompilerServices;
        ///
        ///namespace {{Namespace}};
        ///
        ///partial class {{ClassN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RPGEntityTemplate {
            get {
                return ResourceManager.GetString("RPGEntityTemplate", resourceCulture);
            }
        }
    }
}
