// "Unreal Pokémon" created by Retro & Chill.


#include "Globals/PropertyTraits.h"
#include "Globals/PropertyRegistration.h"

DEFINE_PRIMITIVE_PROPERTY(FBoolProperty);
DEFINE_PRIMITIVE_PROPERTY(FInt8Property);
DEFINE_PRIMITIVE_PROPERTY(FByteProperty);
DEFINE_PRIMITIVE_PROPERTY(FInt16Property);
DEFINE_PRIMITIVE_PROPERTY(FUInt16Property);
DEFINE_PRIMITIVE_PROPERTY(FIntProperty);
DEFINE_PRIMITIVE_PROPERTY(FUInt32Property);
DEFINE_PRIMITIVE_PROPERTY(FInt64Property);
DEFINE_PRIMITIVE_PROPERTY(FUInt64Property);
DEFINE_PRIMITIVE_PROPERTY(FFloatProperty);
DEFINE_PRIMITIVE_PROPERTY(FDoubleProperty);
DEFINE_PRIMITIVE_PROPERTY(FNameProperty);
DEFINE_PRIMITIVE_PROPERTY(FStrProperty);
DEFINE_PRIMITIVE_PROPERTY(FTextProperty);