// "Unreal Pokémon" created by Retro & Chill.

#include "Globals/PropertyRegistration.h"

DEFINE_PROPERTY_REGISTRATION(bool);
DEFINE_PROPERTY_REGISTRATION(int8);
DEFINE_PROPERTY_REGISTRATION(uint8);
DEFINE_PROPERTY_REGISTRATION(int16);
DEFINE_PROPERTY_REGISTRATION(uint16);
DEFINE_PROPERTY_REGISTRATION(int32);
DEFINE_PROPERTY_REGISTRATION(uint32);
DEFINE_PROPERTY_REGISTRATION(int64);
DEFINE_PROPERTY_REGISTRATION(uint64);
DEFINE_PROPERTY_REGISTRATION(float);
DEFINE_PROPERTY_REGISTRATION(double);
DEFINE_PROPERTY_REGISTRATION(FName);
DEFINE_PROPERTY_REGISTRATION(FString);
DEFINE_PROPERTY_REGISTRATION(FText);
DEFINE_PROPERTY_REGISTRATION(FVector);
DEFINE_PROPERTY_REGISTRATION(FRotator);
DEFINE_PROPERTY_REGISTRATION(FTransform);